// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMarkdownContent(arg1:string):Promise<string>;

export function GetMarkdownTree(arg1:string):Promise<main.FileNode>;

export function OpenDirectory():Promise<string>;
