// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMarkdownContent(arg1) {
  return window['go']['main']['App']['GetMarkdownContent'](arg1);
}

export function GetMarkdownTree(arg1) {
  return window['go']['main']['App']['GetMarkdownTree'](arg1);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}
